version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=file:./backend/data/database.sqlite
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  database:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/root/db

volumes:
  sqlite-data:
